ce\models\User:
  type: entity
  table: users
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    username:
      type: string
    password:
      type: string
    mail:
      type: string
    type:
      type: string
  oneToMany:
    posts:
      targetEntity: ce\models\Post
      mappedBy: user
  manyToMany:
    friendsWithMe:
      targetEntity: ce\models\User
      mappedBy: myFriends
    myFriends:
      targetEntity: ce\models\User
      inversedBy: friendsWithMe
      joinTable:
        name: friends
        joinColumns:
          user_id:
            referencedColumnName: id
        inverseJoinColumns:
          friend_user_id:
            referencedColumnName: id